### ISSUE TITLE
[CI/CD] Configure continuous integration for test database isolation

### ISSUE THREAD

**Issue by goodfastcheapPDX** [goodfastcheapPDX/city-council-analyzer#103]
## Description
Update CI workflows to use dedicated test database and ensure proper isolation between CI runs, preventing test interference and ensuring reliable automation.

## Priority
**Priority Level:** P1-Processing

## Dependencies
- [ ] #100 - Create automated test database setup script
- [ ] #101 - Update test environment configuration for isolated database
- [ ] #102 - Migrate storage tests from in-memory to real test database

## Acceptance Criteria
- [ ] CI uses dedicated test database separate from development
- [ ] Test database credentials properly configured in CI secrets
- [ ] Supabase CLI setup automated in CI environment
- [ ] Database reset occurs before each CI test run
- [ ] Multiple CI runs don't interfere with each other
- [ ] CI test results remain consistent and reliable

## Technical Implementation
**Files to Modify:**
- `.github/workflows/*.yml` - Update CI workflow configuration
- Add environment variables to GitHub repository secrets

**CI Configuration Updates:**
```yaml
env:
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.TEST_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.TEST_SUPABASE_ANON_KEY }}

steps:
  - name: Setup Supabase CLI
    run: |
      npm install -g supabase
      supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      
  - name: Reset test database
    run: |
      supabase db reset --project-ref ${{ secrets.TEST_PROJECT_REF }}
      
  - name: Run tests
    run: npm run test
```

**Required Secrets to Add:**
- `TEST_SUPABASE_URL` - Test project API URL
- `TEST_SUPABASE_ANON_KEY` - Test project anonymous key
- `SUPABASE_ACCESS_TOKEN` - CLI authentication token
- `TEST_PROJECT_REF` - Test project reference ID

## Testing Requirements
- [ ] CI workflow completes successfully with isolated test database
- [ ] Test results are consistent across multiple CI runs
- [ ] No test failures due to database state pollution
- [ ] CI runtime remains reasonable (test database reset <30s)
- [ ] Parallel CI jobs (if any) properly isolated
- [ ] CI works for both main branch and pull requests

## Definition of Done
- [ ] CI uses completely isolated test database
- [ ] Test database resets automatically before each CI run
- [ ] CI secrets properly configured and working
- [ ] All tests pass reliably in CI environment
- [ ] No interference between consecutive CI runs
- [ ] Documentation updated with CI setup instructions
